config/routes.rb
Rails.application.routes.draw do
  resources :games, only: %i[new create show index update index]
  resources :players, only: %i[index]

  root 'players#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/circuit.rb
# frozen_string_literal: true

class Circuit < ApplicationRecord
  has_many :games
  has_many :game_players, through: :games, source: :game_players

  validates :name, uniqueness: true, presence: true

  def winner
    game_players.select('player_id, sum(score) as total_score').group(:player_id).order(total_score: :desc).first
  end
end

app/models/game.rb
# frozen_string_literal: true

class Game < ApplicationRecord
  before_validation :default_options

  belongs_to :circuit
  has_many :game_players
  has_many :players, through: :game_players

  validates :laps, inclusion: { in: (1..7) }
  validates :difficulty, inclusion: { in: %w[easy medium hard],
                                      message: 'Value must be easy, medium or hard' }
  validates :mirror, inclusion: { in: [true, false] }

  # default_scope -> { order(created_at: :desc) }
  scope :in_progress, -> { where(finished: false) }
  scope :history, -> { where(finished: true) }

  def winner
    game_players.order(position: :asc).first
  end

  private

  def default_options
    self.laps ||= 7
    self.difficulty ||= 'hard'
    self.mirror ||= false
  end
end

app/models/game_player.rb
# frozen_string_literal: true

class GamePlayer < ApplicationRecord
  belongs_to :player
  belongs_to :game
  has_one :circuit, through: :game, source: :circuit

  before_save :calc_score

  scope :total_scores, -> { select(:player_id, 'sum(score) as total_score').group('player_id').order(total_score: :desc) }

  def self.world_king
    max_score = total_scores.first.total_score
    best_players = total_scores.count do |t|
      t.total_score == max_score
    end
    best_players == 1 ? total_scores.first : nil
  end

  private

  def calc_score
    self.score = case position
                 when 1
                   3
                 when 2
                   2
                 when 3
                   1
                 else
                   0
                 end
  end
end

app/models/player.rb
# frozen_string_literal: true

class Player < ApplicationRecord
  has_many :game_players
  has_many :games, through: :game_players

  validates :name, uniqueness: true, presence: true

  def self.king
    order
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
# frozen_string_literal: true

class GamesController < ApplicationController
  def new
    @circuits = Circuit.all
    @players = Player.all
  end

  def create
    @game = Game.new
    @game.circuit_id = params[:game][:circuit_id]
    @game.save
    params[:game][:players].each do |id|
      @game.game_players.create(player_id: id) unless id.nil?
    end

    redirect_to @game
  end

  def show
    @game = Game.find(params[:id])
    @game_players = @game.game_players
  end

  def update
    @game = Game.find(params[:id])
    i = 0
    @game.game_players.each do |game_player|
      game_player.update(position: params[:game_results][:positions][i])
      i += 1
    end
    @game.update(finished: true)
    redirect_to @game
  end

  def index
    @players = Player.all
    @games_in_progress = Game.in_progress
    @games_history = Game.history
  end
end

app/controllers/players_controller.rb
# frozen_string_literal: true

class PlayersController < ApplicationController
  def index
    @total_scores = GamePlayer.total_scores
    @circuits = Circuit.all
    @world_king = GamePlayer.world_king
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/game_players_helper.rb
# frozen_string_literal: true

module GamePlayersHelper
end

app/helpers/games_helper.rb
# frozen_string_literal: true

module GamesHelper
end

app/helpers/players_helper.rb
# frozen_string_literal: true

module PlayersHelper
end

app/views/games/index.html.erb
<h1>Todas las Partidas</h1>

<% if @games_history %>
  <h2>Puntaje de Juegos terminados</h2>
  <table>
    <tr>
      <th>Pista</th>
      <th>Jugado el</th>
      <th>Mejor Jugador</th>
      <th>Posici&oacute;n</th>
      <th>Puntaje</th>
    </tr>
    <% @games_history.each do |game|%>
      <tr>
        <td><%= link_to game.circuit.name, game %></td>
        <td><%= game.created_at %></td>
        <td><%= game.winner.player.name %></td>
        <td><%= game.winner.position %></td>
        <td><%= game.winner.score %></td>
      </tr>
    <% end %>
  </table>
<% end %>

<% if @games_in_progress %>
  <h2>Juegos en progreso/sin resultados</h2>
  <table>
    <tr>
      <th>Pista</th>
      <th>Jugado el</th>
    </tr>
    <% @games_in_progress.each do |game|%>
      <tr>
        <td><%= link_to game.circuit.name, game %></td>
        <td><%= game.created_at %></td>
      </tr>
    <% end %>
  </table>
<% end %>

app/views/games/new.html.erb
<%= form_for :game, url: games_path do |f| %>
  <%= f.label :circuit_id, 'Pista: ' %>
  <%= f.select :circuit_id, @circuits.collect{|x| [x.name, x.id]}%>

  <fieldset>
    <legend>Jugadores</legend>
    <% @players.each do |p| %>
        <%= f.check_box(:players, { multiple: true}, p.id, nil)%>
        <%= p.name %><br>
    <% end %>
  </fieldset>
  
  <%= f.submit "Crear nuevo Juego" %>
<% end %>

app/views/games/show.html.erb
<h1><%= @game.circuit.name %></h1>
<span><%= @game.created_at.to_date %></span>

<h2>Resultados:</h2>
<% if @game.finished %>
  <table>
    <tr>
      <th>Nombre</th>
      <th>Posici&oacute;n</th>
      <th>Puntaje</th>
    </tr>
    <% @game_players.each do |game_player| %>
      <tr>
        <td><%= game_player.player.name %></td>
        <td><%= game_player.position %></td>
        <td><%= game_player.score %></td>
      </tr>
    <% end %>
  </table>
<% else %>
  <%= form_for :game_results, url: game_path(@game), method: :patch do |f|%>
    <table>
      <tr>
        <th>Nombre</th>
        <th>Posici&oacute;n</th>
      </tr>

      <% @game_players.each do |game_player| %>
        <tr>
          <td><%= game_player.player.name %></td>
          <td><%= f.number_field :positions, multiple: true, in: (1..8) %></td>
        </tr>
      <% end %>
    </table>
    <%= f.submit "Guardar Posiciones"%>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ctr</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav>
        <ul>
          <li><%= link_to 'Inicio', root_path %></li>
          <li><%= link_to 'Partidas', games_path %></li>
          <li><%= link_to 'Nueva Partida', new_game_path %></li>
        </ul>
      </nav>
    </header>
    <%= yield %>
  </body>
</html>

app/views/players/index.html.erb
<h1>Qui&eacute;n es el rey del juego??</h1>
<% if @world_king %>
  <h2>El rey del juego es <%=@world_king.player.name%> :D</h2>
  <h3>Puntaje: <%= @world_king.total_score %></h3>
<% else %>
  <h2>No hay rey del juego a&uacute;n!!</h2>
<% end %>

<h2>Puntajes Totales</h2>
<table>
  <tr>
    <th>Jugador</th>
    <th>Puntaje</th>
  </tr>

  <% @total_scores.each do |t| %>
    <tr>
      <td><%= t.player.name %></td>
      <td><%= t.total_score %></td>
    </tr>
  <% end %>
</table>

<h1>Las pistas y sus reyes</h1>
<table>
  <tr>
    <th>Pista</th>
    <th>Rey</th>
    <th>Puntaje</th>
  </tr>
  <% @circuits.each do |c| %>
    <% if c.winner %>
      <tr>
        <td><%= c.name %></td>
        <td><%= c.winner.player.name %></td>
        <td><%= c.winner.total_score %></td>
      </tr>
    <% end %>
  <% end %>
</table>